# Generated by Django 4.2.16 on 2024-10-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapaguapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='lat',
            field=models.FloatField(default=22.22222),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='lng',
            field=models.FloatField(default=22.222222),
            preserve_default=False,
        ),
    ]
